### ISSUE TITLE
Can't get device status

### ISSUE THREAD

**Issue by czagatti** [marciogranzotto/hass-smartthinq#11]
Detected my HVAC but I keep getting these error messages:

`2021-04-20 17:57:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.ar_condicionado fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/thinq_v2/climate.py", line 367, in update
    self.check_power()
  File "/config/custom_components/thinq_v2/climate.py", line 336, in check_power
    power = self._ac.get_power()
  File "/usr/local/lib/python3.8/site-packages/wideq/ac.py", line 347, in get_power
    return self.get_status().energy_on_current
  File "/usr/local/lib/python3.8/site-packages/wideq/ac.py", line 459, in energy_on_current
    return self._str_to_num(self.data["airState.energy.onCurrent"])
KeyError: 'airState.energy.onCurrent'`

**Comment by davewatson91** [comment]
I'm not entirely sure on this one. In the code, the `check_power` function is in a try loop, so from my quick look should have caught the exception if it came back from WideQ correctly (which it didn't). Any other hints in your log? 

I could also be completely wrong in my understanding of the code too, just trying to help 👍🏼 .

**Comment by czagatti** [comment]
> I'm not entirely sure on this one. In the code, the `check_power` function is in a try loop, so from my quick look should have caught the exception if it came back from WideQ correctly (which it didn't). Any other hints in your log?
> 
> I could also be completely wrong in my understanding of the code too, just trying to help 👍🏼 .

That's the only lines I'm getting for this integration, but I agree with you this is coming "from above" 🤣

**Comment by czagatti** [comment]
Looking at the JSON from LG I see there is no "airState.energy.onCurrent" but "airState.energy.inCurrent", this is being handled by wideq ac.py `return self._str_to_num(self.data["airState.energy.onCurrent"])` - think changing this would solve this issue (or take me to the next level). But I'm wondering how to change this as the file is on the docker instance?

**Comment by davewatson91** [comment]
Interestingly, my JSON also only has inCurrent (and no onCurrent), yet it works...... (albeit without power measurements coming through). I changed mine to be inCurrent, and it just bugged out - there is possibly more going on. 

You can can enter into a bash script in the docker container with: `sudo docker exec -it <container-name> /bin/bash`

You can then use vi to edit the relevant files to test.

**Comment by evandroprieto** [comment]
Dear Marcio.,
I have the same problem. In my instalation appears my Air Conditions but no Entities are created.

Logger: homeassistant.components.climate
Source: custom_components/thinq_v2/climate.py:225
Integration: Clima (documentation, issues)
First occurred: 20:32:47 (1 occurrences)
Last logged: 20:32:47

Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
    return [
  File "/config/custom_components/thinq_v2/climate.py", line 225, in <listcomp>
    in self._ac.model.value("airState.opMode").options.values()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
    d = self.data["Value"][name]
KeyError: 'airState.opMode'

**Comment by czagatti** [comment]
> Interestingly, my JSON also only has inCurrent (and no onCurrent), yet it works...... (albeit without power measurements coming through). I changed mine to be inCurrent, and it just bugged out - there is possibly more going on.
> 
> You can can enter into a bash script in the docker container with: `sudo docker exec -it <container-name> /bin/bash`
> 
> You can then use vi to edit the relevant files to test.

Thanks @davewatson91, I really appreciate your comments and support. Changed ac.py and that error is gone, no status info on the lovelace card (on/off/heat/etc) though. And the same happens when I try to turn it on (if it's on and I click off, it works haha):

2021-04-20 20:44:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139685296320720] 'NoneType' object has no attribute 'is_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 430, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/thinq_v2/climate.py", line 291, in set_hvac_mode
    if not self._state.is_on:
AttributeError: 'NoneType' object has no attribute 'is_on'

**Comment by davewatson91** [comment]
> Dear Marcio.,
> I have the same problem. In my instalation appears my Air Conditions but no Entities are created.
> 
> Logger: homeassistant.components.climate
> Source: custom_components/thinq_v2/climate.py:225
> Integration: Clima (documentation, issues)
> First occurred: 20:32:47 (1 occurrences)
> Last logged: 20:32:47
> 
> Error adding entities for domain climate with platform thinq_v2
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
> capabilities=entity.capability_attributes,
> File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 190, in capability_attributes
> ATTR_HVAC_MODES: self.hvac_modes,
> File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
> return [
> File "/config/custom_components/thinq_v2/climate.py", line 225, in
> in self._ac.model.value("airState.opMode").options.values()
> File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
> d = self.data["Value"][name]
> KeyError: 'airState.opMode'

I think this is probably more related to Issue #9

**Comment by davewatson91** [comment]
> > Interestingly, my JSON also only has inCurrent (and no onCurrent), yet it works...... (albeit without power measurements coming through). I changed mine to be inCurrent, and it just bugged out - there is possibly more going on.
> > You can can enter into a bash script in the docker container with: `sudo docker exec -it <container-name> /bin/bash`
> > You can then use vi to edit the relevant files to test.
> 
> Thanks @davewatson91, I really appreciate your comments and support. Changed ac.py and that error is gone, no status info on the lovelace card (on/off/heat/etc) though. And the same happens when I try to turn it on (if it's on and I click off, it works haha) - error below. I'll change climate.py 291 commenting this to test...
> 
> 2021-04-20 20:44:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139685296320720] 'NoneType' object has no attribute 'is_on'
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
> await hass.services.async_call(
> File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
> task.result()
> File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
> await handler.job.target(service_call)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
> await self.hass.helpers.service.entity_service_call(
> File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
> future.result() # pop exception if have
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
> await coro
> File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
> await result
> File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 430, in async_set_hvac_mode
> await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
> File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/thinq_v2/climate.py", line 291, in set_hvac_mode
> if not self._state.is_on:
> AttributeError: 'NoneType' object has no attribute 'is_on'

This now appears to be the same (unresolved) error as in issue #9

**Comment by davewatson91** [comment]
> > Interestingly, my JSON also only has inCurrent (and no onCurrent), yet it works...... (albeit without power measurements coming through). I changed mine to be inCurrent, and it just bugged out - there is possibly more going on.
> > You can can enter into a bash script in the docker container with: `sudo docker exec -it <container-name> /bin/bash`
> > You can then use vi to edit the relevant files to test.
> 
> Thanks @davewatson91, I really appreciate your comments and support. Changed ac.py and that error is gone, no status info on the lovelace card (on/off/heat/etc) though. And the same happens when I try to turn it on (if it's on and I click off, it works haha) - error below. I'll change climate.py 291 commenting this to test...
> 
> 2021-04-20 20:44:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139685296320720] 'NoneType' object has no attribute 'is_on'
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
> await hass.services.async_call(
> File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
> task.result()
> File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
> await handler.job.target(service_call)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
> await self.hass.helpers.service.entity_service_call(
> File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
> future.result() # pop exception if have
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
> await coro
> File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
> await result
> File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 430, in async_set_hvac_mode
> await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
> File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/thinq_v2/climate.py", line 291, in set_hvac_mode
> if not self._state.is_on:
> AttributeError: 'NoneType' object has no attribute 'is_on'

This is the same error now as issue #9 - would be interesting to see you JSON to see what is listed...

**Comment by czagatti** [comment]
> This is the same error now as issue #9 - would be interesting to see you JSON to see what is listed...

That's easy, here is my JSON :-)

Also tried changing the property to totalCurrent, no success.... Trying outCurrent now to see if it works

[3588e1b5-e086-48ff-8cd5-ae62c38f821c.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6347207/3588e1b5-e086-48ff-8cd5-ae62c38f821c.txt)

**Comment by czagatti** [comment]
nope, can't find a way to make it work... the command "off" is the only one going through 
I wish I had more dev skills to debug what's happening, but I really appreciate your support @davewatson91

**Comment by davewatson91** [comment]
It looks like that's part of a function to pass back to the HA. This is pretty far out of my depth here, but I would add a debug line in around 287, (something to the effect of `_LOGGER.debug("Set %s hvac_mode %s", self.name, hvac_mode)` to see what is actually being passed into that function..

**Comment by davewatson91** [comment]
> > This is the same error now as issue #9 - would be interesting to see you JSON to see what is listed...
> 
> That's easy, here is my JSON :-)
> 
> Also tried changing the property to totalCurrent, no success.... Trying outCurrent now to see if it works
> 
> [3588e1b5-e086-48ff-8cd5-ae62c38f821c.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6347207/3588e1b5-e086-48ff-8cd5-ae62c38f821c.txt)

Interestingly, our JSON files aren't drastically different (there are differences, but nothing that stands out to why yours isn't working) - I suspect it's your local setup  more than the JSON return maybe?

**Comment by czagatti** [comment]
> Interestingly, our JSON files aren't drastically different (there are differences, but nothing that stands out to why yours isn't working) - I suspect it's your local setup more than the JSON return maybe?

it's a fairly new HA install.... Restarting from scratch with the integration and I'll add the debug lines to see if we can get any other detail on this.

**Comment by czagatti** [comment]
Hmmm... you got me thinking about it (local setup). The ac.py from wideq (https://github.com/sampsyo/wideq/blob/master/wideq/ac.py) it doesn't have a line # 459. Deleted the folder wideq from my site-packages directory but it came back there... Does that ring any bell? Would that be something to work with @davewatson91?

**Comment by davewatson91** [comment]
marciogranzotto/hass-smartthinq should have a dependency (and therefore pull) from the [marciogranzotto/wideq](https://github.com/marciogranzotto/wideq) repo (which should have the right content).

**Comment by davewatson91** [comment]
I haven't dug into the differences, but there certainly are a bunch.

**Comment by czagatti** [comment]
Just to share that ollo69 is working on the main ha-smartthinq-sensors implementation at
https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.7.0b2
This tag is working fine for me and other users who tested, but it's still WIP
