### ISSUE TITLE
Error adding entities

### ISSUE THREAD

**Issue by cold-flirtz** [marciogranzotto/hass-smartthinq#14]
Hi, I follow your installation method via HACS and add the integration.
The hass is able to detect my Air Conditioner
![image](https://user-images.githubusercontent.com/55838314/115743517-f1732880-a3bb-11eb-9f41-7e825b0d25b4.png)

But after that it only show 1 devices and no entity at all
![image](https://user-images.githubusercontent.com/55838314/115743639-0c459d00-a3bc-11eb-8375-4ffae752f837.png)

Then when i check the log here is what I found:

> 2021-04-22 22:28:40 ERROR (MainThread) [homeassistant.components.sensor] The thinq_v2 platform for the sensor integration does not support platform setup. Please remove it from your config.
2021-04-22 22:28:40 ERROR (MainThread) [homeassistant.components.climate] The thinq_v2 platform for the climate integration does not support platform setup. Please remove it from your config.
2021-04-22 22:28:42 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 225, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-04-22 22:28:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 225, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'

Please help to fix the integration, let me know if I need to provide more supporting data to help you in the process.

**Comment by olig31** [comment]
> Hi, I follow your installation method via HACS and add the integration.
> The hass is able to detect my Air Conditioner
> ![image](https://user-images.githubusercontent.com/55838314/115743517-f1732880-a3bb-11eb-9f41-7e825b0d25b4.png)
> 
> But after that it only show 1 devices and no entity at all
> ![image](https://user-images.githubusercontent.com/55838314/115743639-0c459d00-a3bc-11eb-8375-4ffae752f837.png)
> 
> Then when i check the log here is what I found:
> 
> > 2021-04-22 22:28:40 ERROR (MainThread) [homeassistant.components.sensor] The thinq_v2 platform for the sensor integration does not support platform setup. Please remove it from your config.
> > 2021-04-22 22:28:40 ERROR (MainThread) [homeassistant.components.climate] The thinq_v2 platform for the climate integration does not support platform setup. Please remove it from your config.
> > 2021-04-22 22:28:42 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
> > await asyncio.gather(*tasks)
> > File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
> > capabilities=entity.capability_attributes,
> > File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 190, in capability_attributes
> > ATTR_HVAC_MODES: self.hvac_modes,
> > File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
> > return [
> > File "/config/custom_components/thinq_v2/climate.py", line 225, in 
> > in self._ac.model.value("airState.opMode").options.values()
> > File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
> > d = self.data["Value"][name]
> > KeyError: 'airState.opMode'
> > 2021-04-22 22:28:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
> > await asyncio.gather(*tasks)
> > File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
> > capabilities=entity.capability_attributes,
> > File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 190, in capability_attributes
> > ATTR_HVAC_MODES: self.hvac_modes,
> > File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
> > return [
> > File "/config/custom_components/thinq_v2/climate.py", line 225, in 
> > in self._ac.model.value("airState.opMode").options.values()
> > File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
> > d = self.data["Value"][name]
> > KeyError: 'airState.opMode'
> 
> Please help to fix the integration, let me know if I need to provide more supporting data to help you in the process.

Don't you understand the problem? I have a similar problem.

**Comment by adrianrdzv** [comment]
There is already an open issue on the same error: #9
