### ISSUE TITLE
Only 3 of my 5 Wall AC show up in Entities, yet all 5 show up under devices?

### ISSUE THREAD

**Issue by BenRoland75** [marciogranzotto/hass-smartthinq#20]
Any Idea on why this would happen? I am missing 2 AC wall units under entities yet they show up under devices.
![image](https://user-images.githubusercontent.com/82595175/117190440-463b7980-ad94-11eb-9d40-24cd9aca2613.png)
![image](https://user-images.githubusercontent.com/82595175/117190498-5b180d00-ad94-11eb-87d7-d77df963cb34.png)
![image](https://user-images.githubusercontent.com/82595175/117190557-708d3700-ad94-11eb-86a3-9ac0cb84e3d5.png)

Here is the log file.
2021-05-05 10:46:07 WARNING (MainThread) [homeassistant.loader] You are using a custom integration thinq_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-05 10:46:07 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-05 10:46:07 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-05 10:46:15 ERROR (MainThread) [homeassistant.components.sensor] The thinq_v2 platform for the sensor integration does not support platform setup. Please remove it from your config.
2021-05-05 10:46:15 ERROR (MainThread) [homeassistant.components.climate] The thinq_v2 platform for the climate integration does not support platform setup. Please remove it from your config.
2021-05-05 10:46:22 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-05-05 10:46:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-05-05 10:46:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 158, in async_load_platform
assert hass_config, "You need to pass in the real hass config"
AssertionError: You need to pass in the real hass config
2021-05-05 10:46:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 158, in async_load_platform
assert hass_config, "You need to pass in the real hass config"
AssertionError: You need to pass in the real hass config
2021-05-05 10:46:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 158, in async_load_platform
assert hass_config, "You need to pass in the real hass config"
AssertionError: You need to pass in the real hass config
2021-05-05 10:46:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 158, in async_load_platform
assert hass_config, "You need to pass in the real hass config"
AssertionError: You need to pass in the real hass config
2021-05-05 10:46:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 158, in async_load_platform
assert hass_config, "You need to pass in the real hass config"
AssertionError: You need to pass in the real hass config
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 10:46:29 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-05 11:00:43 WARNING (MainThread) [homeassistant.components.light] Updating decora_wifi light took longer than the scheduled update interval 0:00:30
2021-05-05 11:24:00 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.kitchen_lights is taking over 10 seconds

**Comment by BenRoland75** [comment]
I have reinstalled VIA HACS and still have the same issue. 
I notice these errors in my log.
**_2021-05-07 09:31:17 ERROR (MainThread) [homeassistant.components.sensor] The thinq_v2 platform for the sensor integration does not support platform setup. Please remove it from your config.
2021-05-07 09:31:17 ERROR (MainThread) [homeassistant.components.climate] The thinq_v2 platform for the climate integration does not support platform setup. Please remove it from your config._**


Any Ideas?
here is my log file again 

2021-05-07 09:27:36 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-07 09:27:36 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-07 09:27:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration thinq_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:27:58 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-05-07 09:28:48 ERROR (MainThread) [engineio.client] packet queue is empty, aborting

2021-05-07 09:31:18 ERROR (MainThread) [engineio.client] packet queue is empty, aborting
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 473, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
    return [
  File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
    in self._ac.model.value("airState.opMode").options.values()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
    d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant.components.alexa.capabilities] climate.graces_ac (<class 'homeassistant.core.State'>) has unsupported state value 'unknown'
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 91, in async_entity_state_listener
    alexa_properties = list(alexa_changed_entity.serialize_properties())
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 320, in serialize_properties
    yield from interface.serialize_properties()
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 243, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 1060, in get_property
    raise UnsupportedProperty(name)
homeassistant.components.alexa.errors.UnsupportedProperty: thermostatMode
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant.components.alexa.capabilities] climate.hannahs_ac (<class 'homeassistant.core.State'>) has unsupported state value 'unknown'
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 91, in async_entity_state_listener
    alexa_properties = list(alexa_changed_entity.serialize_properties())
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 320, in serialize_properties
    yield from interface.serialize_properties()
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 243, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 1060, in get_property
    raise UnsupportedProperty(name)
homeassistant.components.alexa.errors.UnsupportedProperty: thermostatMode
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant.components.alexa.capabilities] climate.pauls_ac (<class 'homeassistant.core.State'>) has unsupported state value 'unknown'
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 91, in async_entity_state_listener
    alexa_properties = list(alexa_changed_entity.serialize_properties())
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 320, in serialize_properties
    yield from interface.serialize_properties()
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 243, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 1060, in get_property
    raise UnsupportedProperty(name)
homeassistant.components.alexa.errors.UnsupportedProperty: thermostatMode
2021-05-07 09:31:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 473, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
    return [
  File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
    in self._ac.model.value("airState.opMode").options.values()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
    d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-05-07 09:32:47 ERROR (MainThread) [engineio.client] packet queue is empty, aborting
2021-05-07 09:34:15 ERROR (MainThread) [engineio.client] packet queue is empty, aborting

**Comment by BenRoland75** [comment]
They are all the same series of LG wall units with the Wi-Fi built in them. The 3 that show up in entities are two of my 9k and a 12k unit. The two that are not showing up are 18k and 7k. 
model numbers:
LSN090HSV5 = 9k
LSN120HSV5 = 12k
LSN180HSV5 = 18k
LMN079HVT = 7k
I do think HA is seeing them as all the same model number if that matters?

**Comment by BenRoland75** [comment]
This is what I see on my Devices. I wonder if the model number shown is the wifi controller and not the AC wall unit?
![image](https://user-images.githubusercontent.com/82595175/118009790-3cb99080-b303-11eb-8955-d6beb1351613.png)

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
