### ISSUE TITLE
Swing Mode

### ISSUE THREAD

**Issue by davewatson91** [marciogranzotto/hass-smartthinq#4]
When getting this going, I did a band-aid (which obviously breaks if you have a swing capable system), but essentially climate.py line 243, I changed from `if self._swing_mode == SWING_MODE_DEFAULT and self._state is not None:` to `if self._swing_mode != SWING_MODE_DEFAULT and self._state is not None:`

Reason being: I have a ducted unit, which isn't swing capable. Meant that the integration wouldn't start  with the following traceback:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 626, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 336, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 269, in state_attributes
    data[ATTR_SWING_MODE] = self.swing_mode
  File "/config/custom_components/thinq_v2/climate.py", line 245, in swing_mode
    if v[0] == self._state.horz_swing and v[1] == self._state.vert_swing:
  File "/usr/local/lib/python3.8/site-packages/wideq/ac.py", line 440, in horz_swing
    lookup_enum("airState.wDir.hStep", self.data, self.ac)
  File "/usr/local/lib/python3.8/site-packages/wideq/util.py", line 17, in lookup_enum
    return device.model.enum_name(attr, data[attr])
KeyError: 'airState.wDir.hStep'
```

**Comment by davewatson91** [comment]
Just checked out my JSON return, can't actually see why this would be failing...... Hopefully someone else can see something I'm missing. I now suspect that this issue may actually lie with [WideQ ](https://github.com/marciogranzotto/wideq)though, and not here. 


[davewatson91_thinq2_json.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6347106/davewatson91_thinq2_json.txt)

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
