### ISSUE TITLE
Cannot control v2 device

### ISSUE THREAD

**Issue by adrianrdzv** [marciogranzotto/hass-smartthinq#9]
I see the v2 device and entity, but no luck trying to control it or showing the current temperature:
```
2021-04-20 09:57:52 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
    return [
  File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
    in self._ac.model.value("airState.opMode").options.values()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
    d = self.data["Value"][name]
KeyError: 'airState.opMode'
```

And

```
2021-04-20 10:11:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1672426928] 'NoneType' object has no attribute 'is_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 434, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/thinq_v2/climate.py", line 292, in set_hvac_mode
    if not self._state.is_on:
AttributeError: 'NoneType' object has no attribute 'is_on'
```

**Comment by LAKY911** [comment]
Same problem here.

**Comment by davewatson91** [comment]
Interesting, my initial thought is that we possibly need to see your JSON output to understand why it's not returning any opModes...

It would be good to get your JSON. If you can modify your __init__.py file to match the this [commit here](https://github.com/marciogranzotto/hass-smartthinq/pull/5/commits/f395e2754a7aea093a87bd87eaf61df73d84d478) (in a PR now).

You will need to lower your debug level to info to get the JSON url - should look like the below in your HA log (noting I've added an arbitrary url). Download the file at the URL, and we can try see what is going on. 

`2021-04-21 08:03:58 INFO (MainThread) [custom_components.thinq_v2] ThinQ client connected
2021-04-21 08:03:58 INFO (MainThread) [custom_components.thinq_v2] Starting LGE ThinQ devices...
2021-04-21 08:03:58 INFO (MainThread) [custom_components.thinq_v2] Found LGE Device with Name: Air Conditioner - Type: AC - InfoUrl: https://objectcontent.lgthinq.com/0990f6af-e7f6-4a12-8388-b9d777b173fb?hdnts=exp=1681202468~hmac=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2021-04-21 08:03:58 INFO (MainThread) [custom_components.thinq_v2] Founds 2 LGE device(s)
`

**Comment by adrianrdzv** [comment]
From my devices:
v2 model json: 
[825eb5cb-0f82-47f8-96ce-5c333587607e.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6347555/825eb5cb-0f82-47f8-96ce-5c333587607e.txt)

v1 model json:
[d27e24f0-7149-11d3-80bf-b4e62abd8d5d.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6347556/d27e24f0-7149-11d3-80bf-b4e62abd8d5d.txt)

**Comment by olig31** [comment]
Same problem

**Comment by cold-flirtz** [comment]
I have the same problem

I follow the installation method via HACS and add the integration.
The hass is able to detect my Air Conditioner
![image](https://user-images.githubusercontent.com/55838314/115743517-f1732880-a3bb-11eb-9f41-7e825b0d25b4.png)

But after that it only show 1 devices and no entity at all
![image](https://user-images.githubusercontent.com/55838314/115743639-0c459d00-a3bc-11eb-8375-4ffae752f837.png)

Then when i check the log here is what I found:

> 2021-04-22 22:28:40 ERROR (MainThread) [homeassistant.components.sensor] The thinq_v2 platform for the sensor integration does not support platform setup. Please remove it from your config.
2021-04-22 22:28:40 ERROR (MainThread) [homeassistant.components.climate] The thinq_v2 platform for the climate integration does not support platform setup. Please remove it from your config.
2021-04-22 22:28:42 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 225, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-04-22 22:28:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 225, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'

Please help to fix the integration, let me know if I need to provide more supporting data to help you in the process.

**Comment by olig31** [comment]
Hello, I have AC LG PC09SQ(RAC_056905_RU), sensors and entities are not created either. Error log:

Copy to clipboard
Logger: homeassistant.components.climate
Source: custom_components/thinq_v2/climate.py:225
Integration: Климат (documentation, issues)
First occurred: 23 апреля 2021 г., 15:17:57 (1 occurrences)
Last logged: 23 апреля 2021 г., 15:17:57

Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/thinq_v2/climate.py", line 221, in hvac_modes
    return [
  File "/config/custom_components/thinq_v2/climate.py", line 225, in <listcomp>
    in self._ac.model.value("airState.opMode").options.values()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
    d = self.data["Value"][name]
KeyError: 'airState.opMode'

**Comment by sbrighty** [comment]
Looks like I have the same error. Closing the duplicate issue. https://github.com/marciogranzotto/hass-smartthinq/issues/19

**Comment by BenRoland75** [comment]
I have the same Error Issue #20

**Comment by lanuaradiego** [comment]
I have the same error

**Comment by adrianrdzv** [comment]
@BenRoland75 Do you know if it works with mixed v1 and v2 devices? Or only v2 devices?

**Comment by czagatti** [comment]
> @BenRoland75 Do you know if it works with mixed v1 and v2 devices? Or only v2 devices?

ollo69's component is working with both v1 and v2 - you just have to install it manually (get the last tag) on your HA

**Comment by sbrighty** [comment]
@BenRoland75 thanks, working for me also.

**Comment by adrianrdzv** [comment]
@BenRoland75 @czagatti It works with both my v1 and v2 devices! Finally. Thanks for the heads up.
